export const EVENT_NAMES = {
  COMMITMENT_WINDOW_ENDING: 'COMMITMENT_WINDOW_ENDING',
  COMMITMENT_WINDOW_ENDED: 'COMMITMENT_WINDOW_ENDED',
  UPKEEP: 'UPKEEP',
  COMMIT: 'COMMIT',
  COMMITS_EXECUTED: 'COMMITS_EXECUTED'
} as const;
